### ISSUE TITLE
Png is created but it is blank

### ISSUE THREAD

**Issue by Ashish117** [steel1990/tga#2]
When running it will create an empty png file.

**Comment by steel1990** [comment]
Can you list your code and the tga file?

**Comment by Ashish117** [comment]
```
var TGA = require("tga");
const maps = "./maps/";
var fs = require("fs");
var PNG = require("pngjs").PNG;
// Delete ds store before start
fs.readdir(maps, function (err, filenames) {
  filenames.forEach(function (filename) {
    console.log(maps + filename); 
    var tga = new TGA(fs.readFileSync(maps + filename));
    var png = new PNG({
      width: tga.width,
      height: tga.height,
    });
    png.data = tga.pixels;
    png.pack().pipe(fs.createWriteStream(`${maps}${filename}.png`));
  });
});
```
[Tga link](https://www.zipshare.com/download/eyJhcmNoaXZlSWQiOiJmMzZkMjgyNy1jOWRlLTRjN2UtOWE0Zi1jNDM2NmEyMDg3YWMiLCJlbWFpbCI6ImFtdm85N0BnbWFpbC5jb20ifQ==)

**Comment by steel1990** [comment]
You tga image's alpha channel are all 0, so the output png file is empty!
Maybe you can reset the alpha channel as 255 by the code below: 

```js
for (var i = 3; i < tga.pixels.length; i += 4) {
    // change alpha channel as 255
    tga.pixels[i] = 255;
}
```

**Comment by Ashish117** [comment]
> You tga image's alpha channel are all 0, so the output png file is empty!
> Maybe you can reset the alpha channel as 255 by the code below:
> 
> ```js
> for (var i = 3; i < tga.pixels.length; i += 4) {
>     // change alpha channel as 255
>     tga.pixels[i] = 255;
> }
> ```

The image is flipped

**Comment by steel1990** [comment]
Please update to the new version, I fixed this issue.
