### ISSUE TITLE
Can only handle image type 2 and 10

### ISSUE THREAD

**Issue by raDiesle** [steel1990/tga#3]
Hello, I try to read in tga file.

It throws error of:

````
Can only handle image type 2 and 10
````

What does it exactly mean and how to fix it?

**Comment by steel1990** [comment]
Can you send your TGA file and let me check it?

**Comment by steel1990** [comment]
Supported the type of 1,3,9,11.

**Comment by raDiesle** [comment]
Seems I forgot to attach a TGA example file. If still helpful here are examples: https://github.com/raDiesle/rise-of-legions/tree/main/Graphics/Units/Black/Frostgoyle

And here: https://www.dropbox.com/s/69sfi5sfstjrnuu/CC%20Assets%20f%C3%BCr%20Deckbuilder.zip?dl=0&file_subpath=%2FCardIcons

**Comment by steel1990** [comment]
I checked your tga files, they were all handled correctly. And  I updated the parser a few hours ago. If you find the wrong file, please tell me which one it is. Thanks.
